#!/usr/bin/env python3
"""Render index.html from content.toml + template.html.

Standard library only. After editing content.toml, run:

    python3 build.py

Prose fields may use `backticks`, which become inline <code> on the page.
"""

import html
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).parent
CONTENT = ROOT / "content.toml"
TEMPLATE = ROOT / "template.html"
OUTPUT = ROOT / "index.html"

GITHUB = "https://github.com"


class ContentError(Exception):
    """A problem in content.toml, reported without a traceback."""


def need(entry, key, where):
    """Fetch a required field, naming the offending entry if it is missing."""
    try:
        return entry[key]
    except KeyError:
        raise ContentError(f"{where} is missing a `{key}` field: {entry!r}") from None


def text(value):
    """Escape HTML, then render `backticks` as inline code."""
    escaped = html.escape(str(value), quote=False)
    return re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)


def attr(value):
    """Escape a value for use inside a double-quoted attribute."""
    return html.escape(str(value), quote=True)


def render_links(links):
    return " &middot; ".join(
        f'<a href="{attr(l["url"])}">{text(l["label"])}</a>' for l in links
    )


def render_projects(projects):
    lines = []
    for p in projects:
        where = f"[[projects]] \"{p.get('name', '?')}\""
        item = f'  <li><a href="{attr(need(p, "url", where))}">{text(need(p, "name", where))}</a>'
        if "stars" in p:
            item += f' <small>{p["stars"]} stars</small>'
        item += f'<br>{text(need(p, "blurb", where))}'
        if p.get("tags"):
            item += f'<br><small>{text(" · ".join(p["tags"]))}</small>'
        lines.append(item + "</li>")
    return "\n".join(lines)


def render_oss(repos):
    blocks = []
    for entry in repos:
        repo = need(entry, "repo", "[[oss.repos]]")
        lines = [f'<h3><a href="{attr(f"{GITHUB}/{repo}")}">{text(repo)}</a></h3>', "<ul>"]
        if "note" in entry:
            lines.append(f'  <li>{text(entry["note"])}</li>')
        for pr in entry.get("prs", []):
            num = need(pr, "num", f"a PR of [[oss.repos]] {repo}")
            title = need(pr, "title", f"{repo}#{num}")
            url = f"{GITHUB}/{repo}/pull/{num}"
            item = f'  <li><a href="{attr(url)}">#{num}</a>'
            if pr.get("date"):
                item += f' <small>{text(pr["date"])}</small>'
            item += f" {text(title)}"
            if pr.get("also"):
                item += f' <small>{text(pr["also"])}</small>'
            if pr.get("open"):
                item += " <small>(open)</small>"
            lines.append(item + "</li>")
        lines.append("</ul>")
        blocks.append("\n".join(lines))
    return "\n\n".join(blocks)


def render_timeline(entries):
    lines = []
    for e in entries:
        where = f"timeline entry \"{e.get('role', '?')}\""
        item = f'  <li>{text(need(e, "role", where))}, {text(need(e, "org", where))}'
        meta = text(need(e, "when", where))
        if e.get("location"):
            meta += f', {text(e["location"])}'
        item += f"<br><small>{meta}</small>"
        if e.get("blurb"):
            item += f'<br>{text(e["blurb"])}'
        lines.append(item + "</li>")
    return "\n".join(lines)


def main():
    with CONTENT.open("rb") as fh:
        try:
            c = tomllib.load(fh)
        except tomllib.TOMLDecodeError as exc:
            raise ContentError(f"{CONTENT.name} is not valid TOML: {exc}") from None

    site = c["site"]
    oss = c["oss"]
    bio = " ".join(site.get("bio", "").split())

    fields = {
        "name": attr(site["name"]),
        "tagline": text(site["tagline"]),
        "description": attr(site["description"]),
        "url": attr(site["url"]),
        "repos_url": attr(site["repos_url"]),
        "source_url": attr(site["source_url"]),
        "bio": f"\n<p>{text(bio)}</p>" if bio else "",
        "links": render_links(site["links"]),
        "projects": render_projects(c["projects"]),
        "oss": render_oss(oss["repos"]),
        "experience": render_timeline(c["experience"]),
        "education": render_timeline(c["education"]),
    }

    page = TEMPLATE.read_text()
    for key, value in fields.items():
        page = page.replace("{{" + key + "}}", value)

    leftover = sorted(set(re.findall(r"\{\{(\w+)\}\}", page)))
    if leftover:
        sys.exit(f"build.py: template placeholder(s) with no content: {', '.join(leftover)}")

    banner = "<!-- GENERATED BY build.py — edit content.toml, not this file. -->\n"
    page = page.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + banner, 1)

    OUTPUT.write_text(page)
    print(f"build.py: wrote {OUTPUT.name} ({len(page.splitlines())} lines)")


if __name__ == "__main__":
    try:
        main()
    except ContentError as exc:
        sys.exit(f"build.py: {exc}")
